export const serwis = {
  url: {
    facebook: "https://www.facebook.com/100063811592941",
    // google: "https://g.co/kgs/XdcEw7o",
    google: "https://www.google.com/search?sa=X&sca_esv=abe1c9b2def561d9&rlz=1C1GCEU_plPL1160PL1161&cs=1&hl=pl&tbm=lcl&sxsrf=AHTn8zqTCrCvzpxP5br2IT0kYal-KQ-nYQ:1747634260820&q=Naprawa%20pralek%20i%20sprz%C4%99tu%20RTV%20-%20naprawa%20ekspres%C3%B3w%20do%20kawy%2C%20naprawa%20telewizor%C3%B3w%2C%20naprawa%20zmywarki%2C%20serwis%20agd%2C%20Opinie&rflfq=1&num=20&stick=H4sIAAAAAAAAAONgkxIxtDA0NzUzNjM3MTWyMDA2NTExN9jAyPiKscwvsaAosTxRAUjmpGYrZCoUFxRVHZlZUqoQFBKmoKuQB5VPzQZKpBYf3lyukJKvkJ1YXqkDlytJzUktz6zKLwLKIkSrcivLE4uyM3UUilOLyjOLFRLTU3QU_Asy8zJTF7EOkMUAMd-hQA0BAAA&rldimm=18175636745280354470&ved=0CIsCEOX6C2oXChMI4NqL--yujQMVAAAAAB0AAAAAEBY&biw=3127&bih=1197&dpr=1.1#lkt=LocalPoiReviews&arid=ChZDSUhNMG9nS0VQYUNfLS0tNnNUWUZREAE",
    mapaGoogle: "https://maps.google.com/?cid=18175636745280354470",
    addTestimonial: "https://search.google.com/local/writereview?placeid=ChIJrWDpGyR_O0cRpvj4OFLVPPw",
  },
  name: "Naprawa pralek i sprzętu RTV - naprawa ekspresów do kawy, naprawa telewizorów, naprawa zmywarki, serwis agd,",
  subName: "Serwis RTV i AGD",
  email: "piotrek_serwis@wp.pl",
  phone: {
    number: "+48790258612",
    formatted: "+48 790 258 612",
  }, adres: "Generała Józefa Sowińskiego 2, 37-700 Przemyśl",
  reviews: [
    {
      "reveiwFor": "telewizor",
      "author_name": "egon920",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocLeFaeToPvK4IxM7u-evnpZcT-b841ZOKvBOmgumUVbm_O0ug=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Super fachowiec. Mało mówi, za to dużo robi... dobrego :-) W moim 46 calowym Samsungu padło podświetlenie i dzięki temu Panu TV odżył, za stosunkowo nie duże pieniądze, w porównaniu z ceną nowego odpowiednika TV.",
      "time": 1739309092,
    },
    {
      "reveiwFor": "ekspres",
      "author_name": "Marta M",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocKRA0X6LgORfbVanU44l8XjOW-IJJUIFHWTHd7RQiu8Db4dfQ=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Z czystym sumieniem polecam serwis za profesjonalne czyszczenie mojego ekspresu do kawy! Usługa została wykonana szybko i z najwyższą starannością. Ekspres działa teraz jak nowy, a smak kawy zyskał zupełnie nową jakość. Fachowa obsługa, miły kontakt i konkurencyjne ceny sprawiają, że na pewno wrócę przy kolejnych potrzebach. Serdecznie dziękuję za tak świetną pracę!",
      "time": 1726153581,
    },
    {
      "reveiwFor": "pralka",
      "author_name": "Bartosz Zawalski",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocL9kBYJPRN2gJJDEP6WZKkuqM-Wn_a1YmdA0rPIoR3W_Y2beA=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Naprawa pralki, szybka i trafna diagnoza. Realizacja naprawy, praktycznie z dnia na dzień nie licząc czasu oczekiwania na cześć zmienną. Polecam serdecznie Pana zna się na swoim fachu. SZYBKI kontakt i szacun za rzetelność.",
      "time": 1727166486,
    },
    {
      "reveiwFor": "zmywarka",
      "author_name": "Magda Ryzner",
      "profile_photo_url": "https://lh3.googleusercontent.com/a-/ALV-UjVr2VP_YAmNfKDbP-mV52eBkBpcgI6yWQ1SR4vAgK_QaPdQMKU_=s128-c0x00000000-cc-rp-mo-ba3",
      "rating": 5,
      "text": "Już kilkakrotnie Pan Piotr naprawiał nam niedziałające sprzęty AGD. Wszystkie działają do tej pory i mają się dobrze. Bardzo dziękuję Panu Piotrowi za szybką i profesjonalną usługę. Szczerze polecam.",
      "time": 1727075329,
    },
    {
      "reveiwFor": "suszarka",
      "author_name": "m p",
      "profile_photo_url": "https://lh3.googleusercontent.com/a/ACg8ocKMSawUWjzTWhs4s32zarbOVNuEUNu7aZJeNd-kuTXdhkVt=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Super profesjonalizm, przystępne ceny i szybkie terminy - zdecydowanie polecam",
      "time": 1720075559,
    },
    {
      "author_name": "EL-METR INSTALACJE Zbigniew Banasiewicz",
      "profile_photo_url": "https://lh3.googleusercontent.com/a-/ALV-UjUhgXMZOtY6kHJX4P7H85Jj7h41sBXlaf3kQFJnt2Zjwxw57KmG=s128-c0x00000000-cc-rp-mo",
      "rating": 5,
      "text": "Pan z ogromną wiedzą i doświadczeniem. Już kilka napraw za nami , wszystko naprawione i działa. Polecam Pana Piotra. Najlepszy elektronik w mieście. Pozdrawiam",
      "time": 1684091120,
    },
  ],
  ratingsTotal: 62,
  rating: 4.6,
  types: [
    "point_of_interest",
    "establishment"
  ],
};
