name: Build and Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 0 * * *"
    # - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: single-workflow
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install lftp
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: sudo apt-get install -y lftp

      - name: Pobierz plik reviews.json
        run: |
          echo "Pobieranie pliku reviews.json z FTP"
          lftp -f "
          open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}
          set xfer:clobber on
          cd /public_html/data/serwis
          cls reviews.json && (
            get reviews.json -o reviews.json
          ) || echo 'Plik reviews.json nie istnieje. Operacja pominięta.'
          quit
          "
