name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz pierwszy plik JSON
        run: curl -o updatedReviews.json https://naprawaprzemysl.pl/api/updatedReviews.json

      - name: Pobierz drugi plik JSON
        run: curl -o reviews.json https://naprawaprzemysl.pl/api/reviews.json

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the application
        env:
          NEXT_PUBLIC_SERVICE_ID: ${{ secrets.SERVICE_ID }}
          NEXT_PUBLIC_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          NEXT_PUBLIC_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          NEXT_PUBLIC_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          NEXT_PUBLIC_PLACE_ID: ${{ secrets.PLACE_ID }}
        run: npm run build

      - name: Install lftp
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: sudo apt-get install -y lftp

      - name: Define dynamic folder name
        run: echo "COPY_FOLDER_NAME=serwis_$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Deploy to FTP
        run: |
          lftp -f "
          open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}
          lcd ./out
          mirror -R . /public_html/serwis
          mirror -R . /public_html/${{ env.COPY_FOLDER_NAME }}
          quit
          "

      - name: Copy .htaccess
        run: |
          lftp -f "
          open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}
          cd /public_html/env/serwis
          get .htaccess -o .htaccess
          put .htaccess -o /public_html/serwis/api/.htaccess
          put .htaccess -o /public_html/${{ env.COPY_FOLDER_NAME }}/api/.htaccess
          quit
          "

      - name: Copy updatedReviews.json
        run: |
          lftp -f "
          open ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}
          cd /public_html/serwis/api
          if [ -f updatedReviews.json ]; then
            get updatedReviews.json -o reviews.json
            put reviews.json -o /public_html/serwis/api/reviews.json
            put reviews.json -o /public_html/${{ env.COPY_FOLDER_NAME }}/api/reviews.json
          else
            echo 'File updatedReviews.json does not exist. Skipping upload.'
          fi
          quit
          "
